package convenientadditions.network;

import convenientadditions.api.network.PacketEntitySpecialItemBehaviours;

public class CAEntitySpecialItemBehavioursPacket extends PacketEntitySpecialItemBehaviours<CAEntitySpecialItemBehavioursPacket> {

}
